version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/environment/my_project
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
