#!/bin/bash

# 프로젝트 디렉토리로 이동
cd /home/ubuntu/environment/

# 최신 코드 가져오기
git pull origin master

# .env 파일 생성 또는 업데이트
cat > .env <<EOL
SECRET_KEY=${SECRET_KEY}
PUBLIC_IP=${PUBLIC_IP}
DATABASES_ENGINE=${DATABASES_ENGINE}
DATABASES_NAME=${DATABASES_NAME}
DATABASES_USER=${DATABASES_USER}
DATABASES_PASSWORD=${DATABASES_PASSWORD}
DATABASES_HOST=${DATABASES_HOST}
DATABASES_PORT=${DATABASES_PORT}
TOPIC_ARN=${TOPIC_ARN}
SUB_EMAIL_ARN=${SUB_EMAIL_ARN}
SUB_MOBILE_ARN=${SUB_MOBILE_ARN}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
AWS_REGION=${AWS_REGION}
EOL
